image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy
  - jmeter

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: $DOCKER_USERNAME/$CI_PROJECT_NAME
  PROJECT_ID: almari-ecc12
  SERVICE_NAME: pre-nerf-spotify-radio
  REGION: asia-southeast1  # e.g., us-central1

# variables:
#   DOCKER_DRIVER: overlay2
#   DOCKER_IMAGE: $DOCKER_USERNAME/$CI_PROJECT_NAME

before_script:
  - docker info
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build:
  stage: build
  script:
    - docker build --build-arg="SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID"
                   --build-arg="SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET"
                   --build-arg="SPOTIFY_REDIRECT_URI=$SPOTIFY_REDIRECT_URI"
                   -t $DOCKER_IMAGE .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE:latest

test:
  stage: test
  script:
    - docker run -d -p 3000:3000 --name test-container $DOCKER_IMAGE:latest
    # add another command that reads the log
    - docker container logs test-container

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: http://your-production-url
  only:
    - main

jmeter:
  stage: jmeter
  image: justb4/jmeter:latest
  script:
    - mkdir -p /test-results
    - jmeter -n -t test_plan.jmx -l /test-results/results.jtl -j /test-results/jmeter.log
  artifacts:
    paths:
      - /test-results/

# deploy:
#   stage: deploy
#   script:
#     # Authenticate with Google Cloud
#     - echo $GCLOUD_SERVICE_KEY | base64 -d > ${CI_PROJECT_DIR}/gcloud-service-key.json
#     - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcloud-service-key.json
#     - gcloud config set project $PROJECT_ID

#     # Deploy the Docker image to Google Cloud Run from Docker Hub
#     - gcloud run deploy $SERVICE_NAME --image $DOCKER_IMAGE:latest --region $REGION --platform managed --allow-unauthenticated
#   environment:
#     name: production
#     url: http://your-production-url
#   only:
#     - main
