image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: $DOCKER_USERNAME/$CI_PROJECT_NAME

before_script:
  - docker info
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE --build-arg SPOTIFY_CLIENT_ID=your_spotify_client_id \ --build-arg SPOTIFY_CLIENT_SECRET=your_spotify_client_secret \ --build-arg SPOTIFY_REDIRECT_URI=your_spotify_redirect_uri \ .
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE:latest

test:
  stage: test
  script:
    - docker run -d -p 3000:3000 --name test-container $DOCKER_IMAGE:$CI_COMMIT_SHA
    # add another command that reads the log
    - docker container logs test-container

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: http://your-production-url
  only:
    - main
